/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package climategame;

/**
 *
 * @author Kirjsten
 */
public class Category extends javax.swing.JFrame {
    
    //Variables
    int count=1, sum=0, totalPos = 100;//sum is grade

    /**
     * Creates new form Energy
     */
    public Category() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        question = new javax.swing.JLabel();
        option1 = new javax.swing.JLabel();
        option2 = new javax.swing.JLabel();
        option3 = new javax.swing.JLabel();
        option4 = new javax.swing.JLabel();
        nextButton = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-Water.png"))); // NOI18N
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 490, 450));

        option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-Water-O1.png"))); // NOI18N
        option1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option1MouseClicked(evt);
            }
        });
        getContentPane().add(option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 290, 60));

        option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-water-O2.png"))); // NOI18N
        option2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option2MouseClicked(evt);
            }
        });
        getContentPane().add(option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 290, 60));

        option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-water-o3.png"))); // NOI18N
        option3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option3MouseClicked(evt);
            }
        });
        getContentPane().add(option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 300, 70));

        option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-water-o4.png"))); // NOI18N
        option4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                option4MouseClicked(evt);
            }
        });
        getContentPane().add(option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 290, 70));

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Blue - NextButton.png"))); // NOI18N
        nextButton.setText("jLabel2");
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 390, 90, 80));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Blue - Background.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 490));

        setSize(new java.awt.Dimension(895, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        // change color of background and next button.
        count++;
        
        switch(count)
        {
            case(1)://water
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-Water.png")));
                option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-Water-O1.png")));
                option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-water-O2.png")));
                option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-water-o3.png")));
                option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-water/Q1-water-o4.png")));
                nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Blue - NextButton.png")));
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Blue - Background.png")));
                break;
            case(2)://water
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q2-water/Q2-water.png")));
                option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q2-water/Q2-water-o1.png")));
                option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q2-water/q2-water-o2.png")));
                option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q2-water/q2-water-o3.png")));
                option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q2-water/q2-water-o4.png")));
                break;
                
            case(3)://water
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q3-water/Q3-water.png")));
                option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q3-water/Q3-water-o1.png")));
                option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q3-water/Q3-water-o2.png")));
                option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q3-water/q3-water-o3.png")));
                option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q3-water/Q3-water-o4.png")));
                break;
                
            case(4)://water
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q4-water/Q4-water.png")));
                option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q4-water/Q4-water-o1.png")));
                option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q4-water/Q4-water-o2.png")));
                option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q4-water/Q4-water-o3.png")));
                option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q4-water/Q4-water-o4.png")));
                break;
                
            case(5): //Transportation
                nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Red - Next Button.png")));
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Red - Background.png")));
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-trans/Q1-trans.png")));
                option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-trans/Q1-trans-o1.png")));
                option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-trans/Q1-trans-o2.png")));
                option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-trans/Q1-trans-o3.png")));
                option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-trans/Q1-trans-o4.png")));
                break;
                
            case(6):
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-trans/Q2-trans.png")));
                break;
            case(7):
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-trans/Q3-trans.png")));
                break;
                
            case(8)://Energy
                nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Yellow - Next Button.png")));
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Yellow - Background.png")));
                option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-Energy/Q1-energy-o1.png")));
                option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-Energy/Q1-energy-o2.png")));
                option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-Energy/Q1-energy-o3.png")));
                option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-Energy/Q1-energy-o4.png")));
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-Energy/Q1-energy.png")));
                break;
                
            case(9):
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-Energy/Q2-energy.png")));
                break;
                
            case(10):
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-Energy/Q3-energy.png")));
                break;
                
            case(11)://Recycle
                nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Green - Next Button.png")));
                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Green - Background.png")));
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-rec/Q1-Rec.png")));
                option1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-rec/Q1-rec-o1.png")));
                option2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-rec/Q1-rec-o2.png")));
                option3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-rec/Q1-rec-o3.png")));
                option4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-rec/Q1-rec-o4.png")));
                break;
                
            case(12):
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-rec/Q2-rec.png")));
                break;
                
            case(13):
                question.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Q1-rec/Q3-rec.png")));
                break;
            case(14):
                //close window
               Results result =  new Results(sum);
                       result.setVisible(true);
            default:
                System.out.print("Error");
        }
        
  
        
                
    }//GEN-LAST:event_nextButtonMouseClicked

    private void option1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option1MouseClicked
        //add 5
        sum+=5;
    }//GEN-LAST:event_option1MouseClicked

    private void option2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option2MouseClicked
        //add 4
        sum+=4;
    }//GEN-LAST:event_option2MouseClicked

    private void option3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option3MouseClicked
        //add 3
        sum+=3;
    }//GEN-LAST:event_option3MouseClicked

    private void option4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_option4MouseClicked
        //2
        sum+=2;
    }//GEN-LAST:event_option4MouseClicked


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel nextButton;
    private javax.swing.JLabel option1;
    private javax.swing.JLabel option2;
    private javax.swing.JLabel option3;
    private javax.swing.JLabel option4;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables
}
