/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package climategame;

/**
 *
 * @author Kirjsten
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        funFact = new javax.swing.JLabel();
        startGame = new javax.swing.JLabel();
        mainMenuBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        funFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Fun Facts Button.png"))); // NOI18N
        funFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funFactMouseClicked(evt);
            }
        });
        getContentPane().add(funFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, 50));

        startGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Start Game Button.png"))); // NOI18N
        startGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startGameMouseClicked(evt);
            }
        });
        getContentPane().add(startGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 220, 50));

        mainMenuBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppPackage/Main Menu - Background.png"))); // NOI18N
        getContentPane().add(mainMenuBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 440));

        setSize(new java.awt.Dimension(401, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startGameMouseClicked
        //catergorey class
        new Category().setVisible(true);
    }//GEN-LAST:event_startGameMouseClicked

    private void funFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funFactMouseClicked
        //fun facts eventually
        new Statistics().setVisible(true);
    }//GEN-LAST:event_funFactMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel funFact;
    private javax.swing.JLabel mainMenuBackground;
    private javax.swing.JLabel startGame;
    // End of variables declaration//GEN-END:variables
}
